title: Vinny from space
author: CrumbsUp
email: info@crumbsup.net
description: >-
  this page shows the artwork of vinny from space, who is also the artist of radorables

social:
  twitter: Radix_Food
  instagram: v1nnyfs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
