title: Vinny from space
url: //vinnyfromspace.art
author: CrumbsUp
email: info@crumbsup.net
description: >-
  Vinny is a digital Web3 artist known from Radorables NFT.

social:
  twitter: Radix_Food
  instagram: v1nnyfs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true